# Generated by Django 3.1.5 on 2021-04-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='protin.jpg', null=True, upload_to=''),
        ),
    ]
